export const NAV_ITEMS = [
  {
    id: "home",
    label: "HOME",
    mobileLabel: "HOME",
    path: "/",
    icon: "H",
    iconBg: "#8A5A3A",
    iconColor: "#FFFFFF",
    requiresAuth: false,
  },
  {
    id: "saved",
    label: "나의 플랜",
    mobileLabel: "나의 플랜",
    path: "/saved",
    icon: "S",
    iconBg: "#B7CBAE",
    iconColor: "#1F3D2E",
    requiresAuth: true,
  },
  {
    id: "automation",
    label: "AI 알림 비서",
    mobileLabel: "AI 비서",
    path: "/automation",
    icon: "A",
    iconBg: "#F0D6C4",
    iconColor: "#8A5A3A",
    requiresAuth: true,
  },
  {
    id: "mypage",
    label: "마이페이지",
    mobileLabel: "마이",
    path: "/mypage",
    icon: "M",
    iconBg: "#E3DDC8",
    iconColor: "#1F3D2E",
    requiresAuth: true,
  },
] as const;
